import { library } from "@fortawesome/fontawesome-svg-core";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

import {
  faHouse,
  faUser,
  faCode,
  faRocket,
  faBriefcase,
  faEnvelope,
  faPhone,
  faLocationDot,
  faArrowUp,
  faArrowDown,
  faBars,
  faXmark,
  faGlobe,
  faPalette,
  faBolt,
  faBook,
  faMobileScreen,
  faWrench,
  faLink,
  faLaptopCode,
  faServer,
  faDatabase,
  faCircleCheck,
  faCalendar,
  faBuilding,
  faMessage,
  faPaperPlane,
  faHeart,
  faArrowUpRightFromSquare,
  faGraduationCap,
} from "@fortawesome/free-solid-svg-icons";

import {
  faGithub,
  faLinkedin,
  faReact,
  faJs,
  faHtml5,
  faCss3Alt,
  faBootstrap,
  faNodeJs,
  faNpm,
  faGitAlt,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faHouse,
  faUser,
  faCode,
  faRocket,
  faBriefcase,
  faEnvelope,
  faPhone,
  faLocationDot,
  faArrowUp,
  faArrowDown,
  faBars,
  faXmark,
  faGlobe,
  faPalette,
  faBolt,
  faBook,
  faMobileScreen,
  faWrench,
  faLink,
  faLaptopCode,
  faServer,
  faDatabase,
  faCircleCheck,
  faCalendar,
  faBuilding,
  faMessage,
  faPaperPlane,
  faHeart,
  faArrowUpRightFromSquare,
  faGraduationCap,
  faGithub,
  faLinkedin,
  faReact,
  faJs,
  faHtml5,
  faCss3Alt,
  faBootstrap,
  faNodeJs,
  faNpm,
  faGitAlt
);